name: Inter-Mod Incompatibility
description: Report an incompatibility 
body:
- type: input
  id: targetmod
  attributes:
    label: Incompatible mod
    description: The name of mod that is incompatible
    placeholder: "MyAwesomeThaumcraftAddon"
validtions:
  required: true
- type: input
  id: targetmodlink
  attributes:
    label: Link to said mod
    description: A link to download said incompatible mod.
    placeholder: "https://legacy.curseforge.com/minecraft/mc-mods/tc4tweaks/files/8469102"
validtions:
  required: true
- type: input
  id: tc4tweaksversion
  attributes:
    label: TC4Tweaks Version used
    placeholder: "1.5.22"
- type: textarea
  id: problem
  attributes:
    label: Behavior of incompatibility
    description: A brief description of how to trigger this incompatibility and what happens when it happens. Attach screenshot if you think it could help explain the situation.
    placeholder: |
      Game crash at start...
      When using X item from this mod Y is supposed to happen but instead Z happens when TC4Tweaks is installed...
      Severe unexplained lag...
      
validtions:
  required: true
